version: 2
updates:
  - package-ecosystem: "pip"
    # Dependabot scans pip requirements in this directory.
    directory: "/requirements"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Etc/UTC"
    groups:
      pip-minor-patch-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      pip-security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
