name: c2tools
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6
  - pip

  # Required dependencies
  - boto3
  - c2==0.0.1
  - python-dotenv

  # Optional dependencies
  - setuptools
