name: Update the Main Docs Repository

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-main-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        # v5
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd

      - name: Install dependencies
        uses: ./.github/actions/setup-python-deps
        with:
          requirements-files: "docs/requirements.txt requirements.txt"
          python-version: "3.11"

      - name: Build Sphinx Markdown docs
        run: |
          sphinx-build -b markdown docs/ docs/_build/markdown

      - name: Publish Documents
        # main @ validityBase/docs
        uses: validityBase/docs/publish-docs-action@dae3fa92603ea55c2081dcb6d15aa0ad1a6355cd
        with:
          docs-repo-access-token: ${{ secrets.DOCS_REPO_ACCESS_TOKEN }}
          source-docs-path: 'docs/_build/markdown'
