name: Update the Main Docs Repository

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-main-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
          pip install -r requirements.txt

      - name: Build Sphinx Markdown docs
        run: |
          sphinx-build -b markdown docs/ docs/_build/markdown

      - name: Publish Documents
        uses: validityBase/docs/publish-docs-action@main
        with:
          docs-repo-access-token: ${{ secrets.DOCS_REPO_ACCESS_TOKEN }}
          source-docs-path: 'docs/_build/markdown'
